apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
  name: digitalocean-dns
  namespace: cert-manager
spec:
  encryptedData:
    access-token: AgB/Y5VDtXNqtfbD5IfGSw4Ns9SVIA8fG0vKKPgVfXdeXdaaaLatOISxWYxvSoCotR1Z1L61nHxNJYan8we5YTTFgObeBPorHlWKkWDzplGBun9BsVnsq5H1vak8cQcuhdOdfQzMUBLo6tZDdieao6wf1JjAyK+/fmR8eT4Pf3k4yZgRde+3ztuh56QrXHfQ3GDQZu/2aOvaNz0YhvSvJ6V1mFUfbP7qFq8FRIT/y3owOAooeVmSE4PRTJ5BcltDvAojzMgfBCyo27aiyLqWmhN00d+wMM9kV4c6BRjlxao4P1O6r3Jw5Dwqbkb+9irk0UMXUgXnxSHzbMHOIRChQFnPdL8KKc8y74PxchCQ6IK0UK6r1lW4n2Pzi1hWp0ZW+pelrJXYAZdTDDbunfkwpTFooLw3YffqgNId7VuqjrhJdcnwj+sMBeJCltHUHAd05E+aKW+NS1c1HlxIJnTSWB+kuOI4PBlXbhVBSDUOZ7KBD/nxQTzjZ0zZL7MAfmg67nr7Jhg4gBt8gv6kl980FU7KN1bCGQGKiT8vvNoVyq8c6LulvjcUlukIeX/LU0F2EZTxd6ZP70hQKUxxOX/Jl4YFw1/s+t36GXq475OieoKblH7Wc1Ug63J+PpPqqoAAdlCMxW5gO6mGB30XFtWhmjSSUNgYKefX55RxhZUwqBUWzsxytS3ZbgzLXThuOShh2mmosWYn2d8klN3D5s4rFjp00Wo4u4cgsfk/MHXZWCj5jY90Fx2UObglfK0dalCmheu2E4ay/qy/UE3dbS2/xFqGLo8+S0mS1Q==
  template:
    metadata:
      name: digitalocean-dns
      namespace: cert-manager
